// Re-export from top-level shared validation module
export {
  ValidationErrorCode,
  validationSuccess,
  validationFailure,
  type ValidationErrorCodeType,
  type ValidationResult,
  isPositionInBounds,
  hasCollision,
  validateBuildTowerBasic,
  validateUpgradeTower,
  validateSellTower,
  validateCannonFire,
  type TowerMetaData,
  type Position,
  type CollidableEntity,
  type PlayerValidationState,
  type TowerValidationState,
  type MapBounds,
  validateSpawnMonster,
  type SpawnableMonsterConfig,
  type SpawnerValidationState,
  type TargetPlayerState,
} from '../../../../shared/validation/index.js';
